apiVersion: apps/v1
kind: Deployment
metadata:
  name: botapp007
  labels:
    app: botapp007
spec:
  replicas: 1
  selector:
    matchLabels:
      app: botapp007
  template:
    metadata:
      labels:
        app: botapp007
    spec:
      containers:
      - name: botapp007
        image: nicopaez/telegrambot:0.0.7
        envFrom:
          - configMapRef:
              name: bot007-config-env